spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive # to solve conflict between Spring Web and Cloud Gateway
  boot:
    admin:
      client:
        url: http://localhost:8888 # Register Admin Server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #

#expose helper endpoints for admin server
management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 5000

#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


