spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive # to solve conflict between Spring Web and Cloud Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #


server:
  port: 5000

#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


