spring:
  application:
    name: payment-service
  boot:
    admin:
      client:
        url: http://localhost:8888 # Register Admin Server

  datasource:
    url: jdbc:h2:file:./database/payment_db
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 3000
  servlet:
    context-path: /payments

#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Expose helper endpoints for admin Server
management:
  endpoints:
    web:
      exposure:
        include: "*"