server:
  port: 8000
  servlet:
    context-path: /doctors

spring:
  application:
    name: doctor-service
  boot:
    admin:
      client:
        url: http://localhost:8888 # Register Admin Server

management:
  endpoints:
    web:
      exposure:
        include: "*"



#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

