server:
  port: 8000
  servlet:
    context-path: /doctors

spring:
  application:
    name: doctor-service


#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

