spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:h2:file:./database/patient_db
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

#Change Default port
server:
  port: 9000
  servlet:
    context-path: /patients

#Register our service to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


